spring:
  h2:
    console:
      enabled: true
  datasource:
    name: soft-club
    generate-unique-name: false
server:
  port: 8082
  servlet:
    context-path: /api/v1.0

cbr:
  url: "https://cbr.ru/scripts/XML_daily.asp"

cron:
  profile: "* * 11,16 * * *"
